---

- name: add NOPASSWD to user vagrant TODO = > REMOVE THIS FROM PROD
  lineinfile: dest=/etc/sudoers line="vagrant ALL=(ALL) NOPASSWD:ALL"
  sudo: yes



- name: add key for postgres apt repository
  action: apt_key url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  sudo: yes

- name: add postgres apt repository
  action: apt_repository repo='deb-src http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present
  sudo: yes

- name: update apt
  raw: apt-get install language-pack-en -y
  sudo: yes

- name: configure gongaloo user
  user: name=james shell=/bin/bash groups=admin append=yes
  sudo: yes

- name: install english locale
  raw: apt-get install language-pack-en -y
  sudo: yes

- name: set locale to {{locale}}
  action: command /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}
  sudo: yes



- name: Install required system packages.
  action: apt pkg={{item}} state=installed update-cache=yes state=installed
  sudo: yes
  with_items:
      - build-essential
      - emacs
      - git-core
      - tmux
      - python-setuptools
      - python-pip
      - supervisor
      - python-apt
      - python-pycurl
      - redis-server
      - python-software-properties
      - xvfb
