- name: ensure postgres is installed
  action: apt pkg={{item}} state=installed update-cache=yes
  sudo: yes
  with_items:
    - postgresql-9.3
    - postgresql-server-dev-9.3
    - python-psycopg2


- name: Create postgresql user
  action: postgresql_user user={{dbuser}} password={{dbpassword}} role_attr_flags=CREATEDB,NOSUPERUSER
  sudo_user: postgres
  sudo: yes

- name: Create postgresql user vagrant
  action: postgresql_user user=vagrant password={{dbpassword}} role_attr_flags=CREATEDB,NOSUPERUSER
  sudo_user: postgres
  sudo: yes


- name: ensure database is created
  action: postgresql_db db={{dbname}} owner={{dbuser}} login_host='localhost' login_user={{dbuser}} login_password={{dbpassword}} encoding='UTF-8' lc_ctype='en_US.UTF-8' lc_collate='en_US.UTF-8'
  sudo_user: postgres
  sudo: yes
  register: db_created

- name: ensure user has access to database
  sudo: yes
  sudo_user: postgres
  action: postgresql_user db={{dbname}} user={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure vagrant user has access to database
  sudo: yes
  sudo_user: postgres
  action: postgresql_user db={{dbname}} user=vagrant password={{dbpassword}} priv=ALL
